# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'SocialBlast' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  source 'https://github.com/CocoaPods/Specs.git'
  use_frameworks!

  pod 'DCTAuth', :git => 'https://github.com/danielctull/DCTAuth.git'

end
